"""
Airflow DAG: tech_sales_pipeline
Pipeline type: batch
Environment: production
Generated by: Ved DE Pipeline (Stage 4)
"""
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'pipeline_owner',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    'tech_sales_pipeline',
    default_args=default_args,
    description='tech_sales data pipeline — generated by Ved DE',
    schedule_interval="0 6 * * *",
    catchup=False,
    tags=['tech_sales', 'production', 'batch'],
)


def ingest_bronze(**kwargs):
    """Bronze layer — raw ingestion from source."""
    import subprocess
    from datetime import timedelta as td

    execution_date = kwargs.get('execution_date')
    if execution_date:
        end_date = execution_date
        start_date = execution_date - td(hours=23, minutes=59)
        start_str = start_date.isoformat()
        end_str = end_date.isoformat()
    else:
        start_str = ''
        end_str = ''

    cmd = [
        'python3', 'stage1_understanding.py',
        '--project_name', 'tech_sales',
        '--source', '/tmp/tech_sales.db',
        '--purpose', 'automated pipeline run'
    ]

    if start_str and end_str:
        cmd.extend(['--start_date', start_str, '--end_date', end_str])

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f'Stage 1 failed: {result.stderr}')


def transform_silver(**kwargs):
    """Silver layer — clean, conform, mask PII."""
    import subprocess
    result = subprocess.run(
        ['python3', 'stage3_build.py', '--project_name', 'tech_sales'],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f'Stage 3 failed: {result.stderr}')


def validate_dq(**kwargs):
    """DQ validation — check scorecard against thresholds."""
    import json
    import os
    dq_path = os.path.join(
        os.environ.get('DE_ARTIFACTS_BASE', '/home/node/Music/de-artifacts'),
        'tech_sales', 'stage3', 'dq_scorecard.json'
    )
    with open(dq_path) as f:
        scorecard = json.load(f)
    dq_threshold = int(os.environ.get('DQ_THRESHOLD', '0'))
    score = scorecard.get('dq_score_pct', 100)
    if score < dq_threshold:
        raise ValueError(
            f'DQ score {score}% is below threshold {dq_threshold}%'
        )


task_bronze = PythonOperator(
    task_id='ingest_bronze',
    python_callable=ingest_bronze,
    dag=dag,
)

task_silver = PythonOperator(
    task_id='transform_silver',
    python_callable=transform_silver,
    dag=dag,
)

task_dq = PythonOperator(
    task_id='validate_dq',
    python_callable=validate_dq,
    dag=dag,
)

# For CSV sources: uncomment FileSensor below to wait for manual uploads
# from airflow.sensors.filesystem import FileSensor
# wait_csv = FileSensor(
#     task_id='wait_for_csv',
#     filepath='/path/to/uploads/tech_sales/{ds}.csv',
#     poke_interval=60,
#     timeout=3600,
#     dag=dag,
# )
# wait_csv >> task_bronze >> task_silver >> task_dq

task_bronze >> task_silver >> task_dq
