"""
Airflow DAG: {dag_id}
Pipeline type: {pipeline_type}
Environment: {env}
Generated by: Ved DE Pipeline (Stage 4)
"""
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.sensors.filesystem import FileSensor

default_args = {{
    'owner': '{owner}',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'retries': {retries},
    'retry_delay': timedelta(minutes={retry_delay}),
}}

dag = DAG(
    '{dag_id}',
    default_args=default_args,
    description='{project_name} data pipeline — generated by Ved DE',
    schedule_interval="{schedule}",
    catchup=False,
    tags=['{project_name}', '{env}', '{pipeline_type}'],
)


def ingest_bronze(**kwargs):
    """Bronze layer — raw ingestion from source."""
    import subprocess
    from datetime import timedelta

    # Calculate 24-hour window based on execution_date
    execution_date = kwargs.get('execution_date')
    if execution_date:
        end_date = execution_date
        start_date = execution_date - timedelta(hours=23, minutes=59)
        start_str = start_date.isoformat()
        end_str = end_date.isoformat()
    else:
        start_str = ''
        end_str = ''

    cmd = [
        'python3', 'stage1_understanding.py',
        '--project_name', '{project_name}',
        '--source', '{{{{ var.value.{project_name}_source }}}}',
        '--purpose', 'automated pipeline run'
    ]

    if start_str and end_str:
        cmd.extend(['--start_date', start_str, '--end_date', end_str])

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f'Stage 1 failed: {{result.stderr}}')


def transform_silver(**kwargs):
    """Silver layer — clean, conform, mask PII."""
    import subprocess
    result = subprocess.run(
        ['python3', 'stage3_build.py', '--project_name', '{project_name}'],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f'Stage 3 failed: {{result.stderr}}')


def validate_dq(**kwargs):
    """DQ validation — check scorecard against thresholds."""
    import json
    import os
    dq_path = os.path.join(
        os.environ.get('DE_ARTIFACTS_BASE', '/home/node/Music/de-artifacts'),
        '{project_name}', 'stage3', 'dq_scorecard.json'
    )
    with open(dq_path) as f:
        scorecard = json.load(f)
    dq_threshold = int(os.environ.get('DQ_THRESHOLD', '0'))
    score = scorecard.get('dq_score_pct', 100)
    if score < dq_threshold:
        raise ValueError(f'DQ score {{score}}% is below threshold {{dq_threshold}}%')


task_bronze = PythonOperator(
    task_id='ingest_bronze',
    python_callable=ingest_bronze,
    dag=dag,
)

task_silver = PythonOperator(
    task_id='transform_silver',
    python_callable=transform_silver,
    dag=dag,
)

task_dq = PythonOperator(
    task_id='validate_dq',
    python_callable=validate_dq,
    dag=dag,
)

# For CSV sources in scheduled mode: wait for file upload
# Uncomment and configure if using CSV with manual uploads:
# wait_csv = FileSensor(
#     task_id='wait_for_csv',
#     filepath='/path/to/uploads/{project_name}/{{{{ ds }}}}.csv',
#     poke_interval=60,
#     timeout=3600,
#     dag=dag,
# )
# wait_csv >> task_bronze >> task_silver >> task_dq

task_bronze >> task_silver >> task_dq
